spring:
  application:
    name: BVT_demo
  datasource:
    url: jdbc:postgresql://localhost:5432/filedb
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      ## ddl-auto: create
    show-sql: true
server:
  port: 8080
